trackip/urls.py
from django.contrib import admin
from django.urls import path
from blog import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('dashboard/',views.dashboard, name="dashboard"),
    path('logout/',views.userlogout, name="userlogout"),
    path('signup/',views.signup, name="signup"),
    path('login/',views.userlogin, name="userlogin"),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Post(models.Model):
    title=models.CharField(max_length=150)
    desc=models.TextField()

class Userinfo(models.Model):
    user = models.ForeignKey(User, null=True, blank=True ,on_delete = models.CASCADE)
    clientip=models.CharField(max_length=50)
    clientname=models.CharField(max_length=50)
    clientcount=models.IntegerField(default=100)
    clienttime=models.DateTimeField(auto_now_add=True)
    clienturl=models.CharField(max_length=200)
    clientview = models.CharField(max_length=200) 

blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm,UsernameField
from django.contrib.auth.models import User
from django.utils.translation import gettext,gettext_lazy as _
from . models import Post
from . models import Userinfo


class Signupform(UserCreationForm):
    password1=forms.CharField(label="Password" ,widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password2=forms.CharField(label=" Confirm Password",widget=forms.PasswordInput(attrs={'class':'form-control'}))
    class Meta:
        model=User
        fields=['username','first_name','last_name','email']
        labels={'first_name':'First Name','last_name':'Last Name','email':'Email'}

        widgets={'username':forms.TextInput(attrs={'class':'form-control'}),
                'first_name':forms.TextInput(attrs={'class':'form-control'}),
                'last_name':forms.TextInput(attrs={'class':'form-control'}),
                'email':forms.EmailInput(attrs={'class':'form-control'})}


class Loginform(AuthenticationForm):
    username=UsernameField(widget=forms.TextInput(attrs={'autofocus':True,'class':'form-control'}))
    password=forms.CharField(label=_("Password"),
                             strip=False,widget=forms.PasswordInput
                             (attrs={'autocomplete':'current-password','class':'form-control'})) 
   

class Postform(forms.ModelForm):
    class Meta:
        model=Post
        fields=['title','desc']
        widgets={'title':forms.TextInput(attrs={'class':'form-control'}),
                 'desc':forms.Textarea(attrs={'class':'form-control'})}

blog/views.py
from django.shortcuts import render,HttpResponseRedirect
from . forms import Signupform,Loginform,Postform
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from . models import Post
from .models import Userinfo
from django.contrib.auth .models import Group
from django.core.cache import cache
# from django.utils import timezone
# Create your views here.
import datetime
def home(request):
    posts=Post.objects.all()
    return render (request,'home.html',{'posts':posts})

def dashboard(request):
    if request.user.is_authenticated:
        posts=Post.objects.all()
        user=request.user
        full_name=user.get_full_name()
        ct=cache.get('count',version=user.pk)
        print("Login Count : ",ct)
        now=datetime.datetime.now()
        print(now)
        return render (request,'dashboard.html',{'post':posts, 'full_name':full_name})
    else:
        return HttpResponseRedirect('/login/')


def userlogout(request):
    logout(request)
    return HttpResponseRedirect('/')



def signup(request):
    if request.method=="POST":
       form=Signupform(request.POST)
       if form.is_valid():
           messages.success(request,"Your account Created Sucessfully You Are Author!!")
           form.save()
           form=Signupform()
    else:
        form=Signupform()   
    return render (request,'signup.html',{'form':form})




def userlogin(request):
    if not request.user.is_authenticated:
        if request.method=="POST":
            form=Loginform(request=request,data=request.POST)
            if form.is_valid():
                uname=form.cleaned_data['username']
                # print(uname)
                upass=form.cleaned_data['password']
                user=authenticate(username=uname,password=upass)
                if user is not None:
                    login(request,user)
                    messages.success(request,"Login Sucessfully !!")
                    return HttpResponseRedirect('/dashboard/')
        else:
            form=Loginform()
        return render (request,'login.html',{'form':form})
    else:
        return HttpResponseRedirect('/dashboard/')
    

blog/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>  MINI BLOG  </title>
</head>
<body>
<div class="container-fluid bg-dark">
    {% include 'navbar.html' %}
</div>

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            {% block msg %}
            {% endblock msg %}
        </div>
    </div>
    <div class="row">
       {% block side %} 
       {% endblock side %}

       {% block content %}
       {% endblock content %}
    </div>
</div>

    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

blog/templates/dashboard.html
{% extends 'base.html' %}
{% load static %}

    {% block msg %}
       {% if messages %}
       {% for message in messages %}
           <p {% if message.tags %} class="alert alert-{{message.tags}} mb-5" {% endif %}>{{message}}</p>
       {% endfor %}
       {% endif %}
    {% endblock msg %}

    {% block side %}
    <div class="col-sm-2 text-white my-5 text-center">
    <h4 class="my-5">Profile</h4>
    <h5>{{full_name}}</h5>
    {% comment %} <h4>login time{{ct}}</h4> {% endcomment %}
    {% comment %} {% for group in groups %}
        <p>{{group.name}}</p>
    {% endfor %} {% endcomment %}
    </div>
    {% endblock side %}
{% block content %}
    <div class="col-sm-10">
           <h3 class="text-white my-5" >Dashboard Page</h3>
           {% comment %} <a href="{% url 'addpost' %}" class="btn btn-info">ADD Post</a> {% endcomment %}
            {% comment %} <h4 class="text-center alert alert-info mt-3"><i>Show Post Information </i></h4>
            {% if post %}
                <table class="table table-hover bg-white">
                    <thead>
                        <tr>
                            <th scope="col" style="width:2%">ID</th>
                            <th scope="col" style="width:28%">Title</th>
                            <th scope="col" style="width:55%">Descripition</th>
                            <th scope="col" style="width:15%">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for post in post %}
                        <tr>
                            <th scope="row">{{post.id}}</th>
                            <td>{{post.title}}</td>
                            <td>{{post.desc}}</td>
                            <td class="text-center">
                                {% comment %} <a href="{% url 'updatepost' post.id %}" class="btn btn-warning bt-sm">Edit</a> {% endcomment %}
                                {% comment %} {% if perms.blog.delete_post %}
                                <form action="{% url 'deletepost' post.id %}" method="post" class="d-inline">
                                    {% csrf_token %}
                                    <input type="submit" class="btn btn-danger btn-sm" value="Delete">
                                </form>
                                {% endif %}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <h4 class="text-centeralertalert-warning">No Record</h4>
            {% endif %}     {% endcomment %}
    </div>

{% endblock content %}

blog/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="col-sm-10">
    <h3 class="text-white my-5" >Home Page</h3>
  {% for post in posts %}
    <div class="jumbotron jumbotron-fluid jumbo-color">
        <div class="container">
          <h1 class="display-4 font-weight-bold">{{post.title}}</h1>
          <p class="lead">{{post.desc}}</p>
        </div>
      </div>
  {% endfor %}
</div>

{% endblock content %}

blog/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="col-sm-10">
    <h3 class="text-white my-5" >Login Page</h3>

    <form action="" method='POST'>
        {% csrf_token %} 
            {% for fm in form %}
            <div class="form-group">
                {{fm.label_tag}}{{fm}}{{fm.errors|striptags}}
            </div>
            {% endfor %}<br>
            <input type="submit" value="Login" class="btn btn-info">
</div>

{% endblock content %}

blog/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Mini Blog</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
          {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'dashboard' %}">Dashboard</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'userlogout' %}">Logout</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'signup' %}">Signup</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'userlogin' %}">Login</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

blog/templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="col-sm-10">
    <h3 class="text-white my-5" >SignUp</h3>
    {% if messages %}
        {% for message in messages %}
            <p {% if message.tags %} class="alert alert-{{message.tags}} mb-5" {% endif %}>{{message}}</p>
        {% endfor %}
    {% endif %}


    <form action="" method='POST'>
    {% csrf_token %} 
        {% for fm in form %}
        <div class="form-group"><br>
            {{fm.label_tag}}{{fm}}{{fm.errors|striptags}}
        </div>
        {% endfor %}<br>
        <input type="submit" value="Submit" class="btn btn-info">
    </form>
    
</div>

{% endblock content %}